name = "SumProductNetworks"
uuid = "a22f005f-d29d-4892-833e-0fc2359d1e90"
authors = ["Denis Maua <denis.maua@gmail.com>"]
version = "0.2.0"

[deps]
AlgebraicDecisionDiagrams = "fda02c4b-e729-4157-987e-1560c7fe1ac2"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
GraphicalModels = "a9c32ad1-b399-4167-82a9-e18baef426d8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Clustering = "0.14"
julia = "1.4"
GraphicalModels = "0.1.0"
AlgebraicDecisionDiagrams = "0.1.0"
